# Features

Engineered columns are built by `python -m sbahn.features.build` and saved to `data/processed/trips_features.parquet`. The rules are in `docs/feature_dictionary.md`.

In [2]:
import pandas as pd

from sbahn.config import PROCESSED_DIR

features = pd.read_parquet(PROCESSED_DIR / "trips_features.parquet")
features.head()

,trip_id,line_id,start_station_id,end_station_id,scheduled_departure_time,is_peak_hour,is_delayed,temperature_c,precipitation_mm,wind_speed_kmh,...,rain_at_peak,network_load,line_trips_prev_hour,line_delay_rate_prev_hour,line_mean_delay_prev_hour,line_trips_prev_day,line_delay_rate_prev_day,line_mean_delay_prev_day,start_station_trips_prev_hour,start_station_delay_rate_prev_hour
0,0,S42,S1,S6,2024-08-16 02:31:00,0,0,14.15,3.18,18.56,...,0,23,4,0.0,1.250000,59,0.033898,2.254237,3,0.0
1,1,S2,S4,S7,2024-02-02 18:31:00,1,0,19.17,3.24,25.53,...,1,19,3,0.0,1.666667,59,0.000000,1.423729,1,0.0
2,2,S42,S3,S5,2024-10-11 00:03:00,0,0,5.18,1.81,8.76,...,0,16,2,0.0,1.500000,49,0.061224,2.346939,2,0.0
3,3,S1,S5,S7,2024-08-20 02:04:00,0,0,14.99,0.32,29.85,...,0,17,2,0.0,1.000000,70,0.000000,1.600000,2,0.0
4,4,S7,S5,S6,2024-05-26 03:54:00,0,0,14.69,0.00,27.91,...,0,16,2,0.0,0.000000,66,0.000000,0.681818,3,0.0

In [4]:
pd.set_option("display.max_columns", None)
features.head()

,trip_id,line_id,start_station_id,end_station_id,scheduled_departure_time,is_peak_hour,is_delayed,temperature_c,precipitation_mm,wind_speed_kmh,weather_condition,has_incident,incident_type,event_name,is_event_day,is_strike_day,line_name,is_ring_line,start_name,start_is_major_hub,start_location_category,end_name,end_is_major_hub,end_location_category,hour,day_of_week,month,is_weekend,route_key,location_pair,hub_pattern,is_raining,rain_at_peak,network_load,line_trips_prev_hour,line_delay_rate_prev_hour,line_mean_delay_prev_hour,line_trips_prev_day,line_delay_rate_prev_day,line_mean_delay_prev_day,start_station_trips_prev_hour,start_station_delay_rate_prev_hour
0,0,S42,S1,S6,2024-08-16 02:31:00,0,0,14.15,3.18,18.56,Clear,0,NaN,NaN,0,0,S42 (Ring),1,Berlin Hauptbahnhof,1,city_center,Flughafen BER,0,airport,2,4,8,0,S42|S1|S6,city_center to airport,start,1,0,23,4,0.0,1.250000,59,0.033898,2.254237,3,0.0
1,1,S2,S4,S7,2024-02-02 18:31:00,1,0,19.17,3.24,25.53,Clear,0,NaN,NaN,0,0,S2,0,Friedrichstraße,1,city_center,Alexanderplatz,1,city_center,18,4,2,0,S2|S4|S7,city_center to city_center,both,1,1,19,3,0.0,1.666667,59,0.000000,1.423729,1,0.0
2,2,S42,S3,S5,2024-10-11 00:03:00,0,0,5.18,1.81,8.76,Clear,0,NaN,NaN,0,0,S42 (Ring),1,Potsdam Hauptbahnhof,0,suburb,Olympiastadion,0,event_venue,0,4,10,0,S42|S3|S5,suburb to event_venue,neither,1,0,16,2,0.0,1.500000,49,0.061224,2.346939,2,0.0
3,3,S1,S5,S7,2024-08-20 02:04:00,0,0,14.99,0.32,29.85,Clear,0,NaN,NaN,0,0,S1,0,Olympiastadion,0,event_venue,Alexanderplatz,1,city_center,2,1,8,0,S1|S5|S7,event_venue to city_center,end,1,0,17,2,0.0,1.000000,70,0.000000,1.600000,2,0.0
4,4,S7,S5,S6,2024-05-26 03:54:00,0,0,14.69,0.00,27.91,Clear,0,NaN,NaN,0,0,S7,0,Olympiastadion,0,event_venue,Flughafen BER,0,airport,3,6,5,1,S7|S5|S6,event_venue to airport,neither,0,0,16,2,0.0,0.000000,66,0.000000,0.681818,3,0.0